# Transfer weights from deeplab model and finetune on SUNRGBD

_BASE_: "../Base-RCNN-Deeplab-Resnet.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  PIXEL_MEAN: [103.530, 116.280, 123.675, 18516.75]
  PIXEL_STD: [57.375, 57.120, 58.395, 8811.2]
  WEIGHTS: './pretrained/deeplab_resnet_coco.pkl'
  DEEPLAB:
    MODEL:
      INPUT_CHANNELS: 4
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  USE_DEPTH: True
  MASK_FORMAT: "bitmask"
DATASETS:
  TRAIN: ("sunrgbd_train",)
  TEST: ("sunrgbd_val",)
OUTPUT_DIR: "./output/RGBD_mask_rcnn_R_101_deeplab_sunrgbd"