_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  PIXEL_MEAN: [103.530, 116.280, 123.675, 54.528]
  PIXEL_STD: [57.375, 57.120, 58.395, 28.416]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  USE_DEPTH: True